"""
Report generation from pipeline output.
Doctor report: template-based markdown (fast, deterministic).
Patient report: LLM-generated plain language markdown.
"""
import json
from datetime import date
from shared.llm import chat

PATIENT_PROMPT = """You are writing a personal health summary for a patient with no medical background.
Use simple, clear language anyone can understand. Avoid medical jargon entirely.
When you must use a medical term, explain it in plain words in parentheses immediately after.
Write in second person ("You came in...", "Your body is...").
Be honest, warm, and direct. Do not minimize serious findings, but do not cause unnecessary panic.

Use exactly these four sections:

## What Is Happening
2-3 sentences explaining the diagnosis and current state in plain terms.
Describe what is physically happening inside the body — no jargon.

## Why This Happened
1-2 sentences on the cause or contributing factors. What led to this.

## What We Are Doing About It
Bullet list: specific treatments, medications being given or changed, procedures ordered.
One bullet per action. Plain language — "We are giving you water pills through an IV to remove excess fluid."

## What You Should Do Next
Bullet list: patient instructions, warning signs to watch for, follow-up steps, questions to ask.
Include anything the patient needs to actively do or know before leaving.

Clinical data:

Clinical data:
SOAP Note: {soap}
Risk Flags: {flags}
Medications: {meds}
Summary: {summary}

Return ONLY valid markdown. No code fences. No preamble."""


def generate_doctor_report(result: dict, patient_id: str = "ANON") -> str:
    today = date.today().isoformat()
    soap = result.get("soap_note", {})

    # Flags table
    risk_flags = result.get("risk_flags", [])
    flags_rows = ""
    for f in risk_flags:
        sev = f.get("severity", "LOW")
        icon = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(sev, "⚪")
        evidence = f.get("evidence", "")
        flags_rows += f"| {icon} {sev} | {f.get('flag', '')} | {evidence} |\n"
    if not flags_rows:
        flags_rows = "| — | No critical flags detected | — |\n"

    # Medications table
    meds = result.get("medications", [])
    meds_rows = "".join(
        f"| {m.get('name', '')} | {m.get('dose', '')} | {m.get('frequency', '')} |\n"
        for m in meds
    ) or "| — | None extracted | — |\n"

    # Interactions
    interactions = result.get("interactions", [])
    interaction_block = ""
    if interactions:
        interaction_block = "\n### Drug Interactions (OpenFDA)\n\n"
        for i in interactions:
            warning = i.get("warnings", "")[:300]
            interaction_block += f"**{i.get('drug', '')}:** {warning}...\n\n"

    # Timeline
    events = result.get("timeline_events", [])
    timeline_rows = "".join(
        f"| {e.get('date', '')} | {e.get('event', '')} | {e.get('category', '')} |\n"
        for e in events
    ) or "| — | No events extracted | — |\n"

    # SOAP sections
    def section(label: str, content) -> str:
        if isinstance(content, list):
            body = "\n".join(f"- {item}" for item in content) if content else "_Not available_"
        else:
            body = str(content) if content else "_Not available_"
        return f"**{label}:** {body}"

    trace_id = result.get("trace_id", "")

    return f"""# Clinical Summary Report

**Patient ID:** {patient_id} | **Date:** {today} | **Trace:** `{trace_id}`

---

## Critical Risk Flags

| Severity | Flag | Evidence |
|---|---|---|
{flags_rows}
## SOAP Note

{section("Subjective", soap.get("subjective", ""))}

{section("Objective", soap.get("objective", ""))}

{section("Assessment", soap.get("assessment", ""))}

{section("Plan", soap.get("plan", ""))}

---

## Medication List

| Drug | Dose | Frequency |
|---|---|---|
{meds_rows}{interaction_block}
---

## Medical Timeline

| Date | Event | Category |
|---|---|---|
{timeline_rows}
---

_Generated by ClinicalCopilot. For clinical use only. Always verify with primary source documentation._
"""


def generate_patient_report(result: dict) -> str:
    soap = result.get("soap_note", {})
    flags = result.get("risk_flags", [])
    meds = result.get("medications", [])
    summary = result.get("summary", "")

    try:
        report = chat(
            PATIENT_PROMPT.format(
                soap=json.dumps(soap),
                flags=json.dumps(flags),
                meds=json.dumps(meds),
                summary=summary,
            ),
            max_tokens=900,
        )
        report = report.strip()
        if not report or len(report) < 50:
            raise ValueError("empty response")
        return report
    except Exception:
        # Fallback: minimal template
        flag_lines = "\n".join(
            f"- **{f.get('flag', '')}** ({f.get('severity', '')}): {f.get('evidence', '')}"
            for f in flags
        ) or "- No critical issues detected"

        return f"""## Your Health Summary

{summary or "Your care team analyzed your chart and prepared this summary."}

## Warning Signs Found

{flag_lines}

## What to Expect Next

Please speak with your care team about the plan and any questions you have about your medications or next steps.
"""
